#!/bin/sh
#yu

# <https://github.com/pinterest/ktlint> pre-commit hook

git diff --name-only -z --cached --relative -- '*.kt' '*.kts' | ktlint --relative --patterns-from-stdin=''
java -jar ktlint.jar

